### ISSUE TITLE
PHP Client?

### ISSUE THREAD

**Issue by esokullu** [RedisLabsModules/redis-graph#157]
Is there a PHP client? I've opened a [ticket](https://github.com/nrk/predis/issues/533) with predis, the most popular php Redis client, but I also wanted to check it here.

Thanks,

**Comment by swilly22** [comment]
Hi @esokullu,
It's been awhile since I've worked with PHP (~14 years), regardless RedisGraph clients are quite simple, usually a thin wrapper on-top of Graph.query which gives an easier access to the result-set.
If someone would like to create such a client It would be a welcome contribution, otherwise end of November is a feasible date for us to create one.

**Comment by kjdev** [comment]
I tried to create it.

https://github.com/kjdev/php-redis-graph

**Comment by esokullu** [comment]
Thanks @swilly22 @kjdev
