### ISSUE TITLE
GRAPH.BULK?

### ISSUE THREAD

**Issue by davisford** [RedisLabsModules/redis-graph#190]
No docs on this one?  Curious...

```
127.0.0.1:6379> GRAPH.BULK 
(error) ERR wrong number of arguments for 'GRAPH.BULK' command
127.0.0.1:6379> help graph.bulk

  GRAPH.BULK key ...options...
  summary: Help not available
  since: not known
  group: generic
```

**Comment by jeffreylovitz** [comment]
Sorry about that! Documentation is on our to-do list, but we might opt for a more significant overhaul soon.

This command is used by the Python script at `demo/bulk_insert/bulk_insert.py`, and i would generally recommend using that script instead of native calls to this command, as the format is rather rigid. If you do want to roll your own approach, the comments in that script should prove helpful regardless.

This command interprets sequences of up to ~1 million tokens to construct nodes and/or relations. The specific number of entities, labels, and so forth must be specified in advance, which is part of why it's not terribly user-facing just yet. The Python script handles that tallying, CSV input parsing, and batching.

Happy to help here if you have questions about the process!

**Comment by davisford** [comment]
OK, thanks for the quick, quality response.  I'll close this issue.
