### ISSUE TITLE
Weird result sets

### ISSUE THREAD

**Issue by kdaham** [RedisLabsModules/redis-graph#88]
127.0.0.1:6379> graph.query a "CREATE (jim:person{name:'Jim', age:29})-[friends]->(pam:person {name:'Pam', age:27})-[works]->(:employer {name:'Dunder Mifflin'})"
1) (empty list or set)
2) 1) Labels added: 2
   2) Nodes created: 3
   3) Properties set: 5
   4) Relationships created: 2
   5) "Query internal execution time: 0.350732 milliseconds"
127.0.0.1:6379> graph.query a "MATCH (person)-[friends]->(p:person) RETURN p"
1) 1) 1) "p.age"
      2) "p.name"
   2) 1) "27.000000"
      2) "Pam"
   3) 1) "NULL"
      2) "Dunder Mifflin"
2) 1) "Query internal execution time: 0.081449 milliseconds"
127.0.0.1:6379> graph.query a "MATCH (person)-[works]->(e:employer) RETURN e"
1) 1) 1) "e.name"
   2) 1) "Pam"
   3) 1) "Dunder Mifflin"
2) 1) "Query internal execution time: 0.079909 milliseconds"
127.0.0.1:6379> graph.query a "MATCH (p:person)-[works]->(e:employer) RETURN p"
1) 1) 1) "p.age"
      2) "p.name"
   2) 1) "29.000000"
      2) "Jim"
   3) 1) "27.000000"
      2) "Pam"
2) 1) "Query internal execution time: 0.105995 milliseconds"

Now for all three I did expect to only get one record that matches the label, and if you do the same in neo4j you get one record for each of the queries.

**Comment by jeffreylovitz** [comment]
Thanks for the detailed writeup! It makes it a lot easier to suss out what's going on.

In this case, there is a bug in play here, but there's also a bit of confusion about when aliases are being used and when labels are.

Edges, like nodes, are identified by an alias, a label, or both. If there is no colon in the edge descriptor, the string is assumed to be an alias, where here you want a label. So the correct query would be:
`CREATE (jim:person{name:'Jim', age:29})-[:friends]->(pam:person {name:'Pam', age:27})-[:works]->(:employer {name:'Dunder Mifflin'}`
I expect that only one edge type is being constructed, and the `friends` and `works` aliases in your CREATE query both refer to the same NULL-labeled edge type.

To a degree, we can verify this because aliases don't have meaning past their own query. Using your provided graph:
```
127.0.0.1:6379> GRAPH.QUERY a "MATCH (any_source)-[random_meaningless_alias]->(any_dest) RETURN any_source.name, any_dest.name"
1) 1) 1) "any_source.name"
      2) "any_dest.name"
   2) 1) "Jim"
      2) "Pam"
   3) 1) "Pam"
      2) "Dunder Mifflin"
2) 1) "Query internal execution time: 0.462812 milliseconds"
```
There is an edge between Jim and Pam, and an edge between Pam and Dunder Mifflin - this query used no labels.

`MATCH (person)-[works]->(e:employer) RETURN e` should definitely only return Dunder Mifflin because you specify that the destination should be an `employer`, though it's again important to note that `person` here is an alias and not a label - any source node with an edge to Dunder Mifflin would be returned. The last query provides a label for everything but the edge, but should only return Pam. So those two are the product of a bug. - I expect that we're retrieving all edges and not verifying that the labels on source and destination are correct.

I'm self-assigning this to work on that label validation. The behavior associated with providing an alias without a label, however, is correct as far as I know!

**Comment by jeffreylovitz** [comment]
I'm inclined to agree, I think - there don't seem to be any advantages that outweigh the potential confusions that arise from unlabeled relations.

@swilly22, what are your thoughts?

A bit of reference:
Neo4j response:
```
Neo.ClientError.Statement.SyntaxError
A single relationship type must be specified for CREATE (line 1, column 31 (offset: 30))
"CREATE (a:person {name: 'ee'})-[friend]->(b:banana{name: 'ban'})"
```
Cypher language reference:
`A relationship is assigned exactly one relationship type.`

**Comment by swilly22** [comment]
@kdaham thanks for bringing this to our attention.

I had no idea you're not allowed to create a relation-less edge, we would change the grammar to enforce that (edge will require a single type upon creation),
in addition we're currently not validating the destination entity type which is a bug, I've started working on that during Thursday, we should have a fix early this upcoming week.

I'll update here.
